name: uandi
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.2
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  flutter_riverpod: ^1.0.4
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  intl: ^0.17.0
  another_flushbar: ^1.12.29
  scrollable_positioned_list: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.2.0



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/

  fonts:
    - family: Kangwon
      fonts:
        - asset: fonts/kangwon/강원교육모두 Light.otf
          weight: 400
        - asset: fonts/kangwon/강원교육모두 Bold.otf
          weight: 700

#    - family: Kangwon
#      fonts:
#        - asset: fonts/kangwon/강원교육새음.ttf